# Generated by Django 4.2.2 on 2023-06-25 04:15

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="")),
                ("surname", models.CharField(max_length=250, verbose_name="")),
                ("midname", models.CharField(max_length=250, verbose_name="")),
                ("science_fields", models.CharField(max_length=250, verbose_name="")),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("Доктор наук", "Phd"),
                            ("Кандидат наук", "Lowerphd"),
                            ("Аспирант", "Postgraduate"),
                            ("Магистр", "Master"),
                            ("Отсутствует", "None"),
                        ],
                        default="Отсутствует",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                (
                    "slug",
                    models.SlugField(
                        max_length=250, unique_for_date="publish", verbose_name=""
                    ),
                ),
                (
                    "publish",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 6, 25, 4, 15, 19, 649974, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "ordering": ["-surname"],
                "indexes": [
                    models.Index(
                        fields=["-surname"], name="memebers_me_surname_90ad26_idx"
                    )
                ],
            },
        ),
    ]
