# Generated by Django 4.2.2 on 2023-06-25 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memebers", "0002_alter_member_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.CharField(blank=True, max_length=250, verbose_name=""),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=250, verbose_name=""),
        ),
        migrations.AddField(
            model_name="member",
            name="socials",
            field=models.CharField(blank=True, max_length=250, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="member",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 6, 12, 58, 933395, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
