# Generated by Django 4.2.2 on 2023-06-25 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memebers", "0003_member_email_member_phone_member_socials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 8, 49, 28, 510466, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
