# Generated by Django 4.2.2 on 2023-07-09 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memebers", "0010_alter_member_publish"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="member",
            name="memebers_me_surname_90ad26_idx",
        ),
        migrations.AlterField(
            model_name="member",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Адрес электронной почты"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="users/%Y/%m/%d/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="midname",
            field=models.CharField(max_length=250, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=250, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="member",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 9, 8, 25, 43, 741759, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="rank",
            field=models.CharField(
                choices=[
                    ("Доктор наук", "Phd"),
                    ("Кандидат наук", "Lowerphd"),
                    ("Аспирант", "Postgraduate"),
                    ("Магистр", "Master"),
                    ("Отсутствует", "None"),
                ],
                default="Отсутствует",
                max_length=250,
                verbose_name="Степень/звание",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="science_fields",
            field=models.CharField(
                max_length=250, verbose_name="Область научных интересов"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="slug",
            field=models.SlugField(
                max_length=250, unique_for_date="publish", verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="socials",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Социальные сети"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="surname",
            field=models.CharField(max_length=250, verbose_name="Фамилия"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["-surname", "-publish", "-status"],
                name="memebers_me_surname_3a6d10_idx",
            ),
        ),
    ]
