# Generated by Django 4.2.2 on 2023-06-25 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memebers", "0002_alter_member_publish"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(to="memebers.member"),
        ),
        migrations.AlterField(
            model_name="event",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 4, 56, 35, 676915, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
