# Generated by Django 4.2.2 on 2023-06-25 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_members_alter_event_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="document",
            field=models.FileField(blank=True, upload_to="events/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 5, 20, 15, 385390, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
