# Generated by Django 4.2.2 on 2023-07-05 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_event_publish_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 5, 16, 24, 33, 993748, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
