# Generated by Django 4.2.2 on 2023-07-09 08:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0001_initial"),
        ("memebers", "0011_remove_member_memebers_me_surname_90ad26_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0011_alter_event_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="event_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="members", to="memebers.member"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 9, 8, 25, 43, 744759, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                max_length=250, unique_for_date="publish", verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="event",
            name="viewes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="viewes", to="viewer.viewer"
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="users/%Y/%m/%d/", verbose_name="Изображение"
            ),
        ),
    ]
