# Generated by Django 4.2.2 on 2023-07-11 02:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("memebers", "0012_alter_member_publish"),
        ("viewer", "0001_initial"),
        ("events", "0012_alter_event_likes_alter_event_members_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventimage",
            options={"verbose_name": "event_img", "verbose_name_plural": "event_imgs"},
        ),
        migrations.RemoveField(
            model_name="eventimage",
            name="news",
        ),
        migrations.AddField(
            model_name="eventimage",
            name="event",
            field=models.ManyToManyField(
                blank=True,
                related_name="images",
                to="events.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="body",
            field=models.TextField(verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="document",
            field=models.FileField(
                blank=True, upload_to="events/%Y/%m/%d/", verbose_name="Документ"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="event_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="members",
                to="memebers.member",
                verbose_name="Участники",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 11, 2, 55, 3, 953569, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время публикации",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                max_length=250, unique_for_date="publish", verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published")],
                default="DF",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время обновления"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="viewes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="viewes",
                to="viewer.viewer",
                verbose_name="Просмотры",
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="event/%Y/%m/%d/", verbose_name="Изображение"
            ),
        ),
    ]
