# Generated by Django 4.2.2 on 2023-06-23 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_news_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.AlterField(
            model_name="news",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 23, 16, 46, 11, 876572, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("news", models.ManyToManyField(related_name="images", to="news.news")),
            ],
        ),
    ]
