# Generated by Django 4.2.2 on 2023-06-25 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_remove_news_image_alter_news_publish_newsimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 8, 49, 34, 44770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="newsimage",
            name="news",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="news.news"
            ),
        ),
    ]
