# Generated by Django 4.2.2 on 2023-06-28 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0001_initial"),
        ("news", "0007_alter_news_publish_alter_newsimage_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="viewes",
            field=models.ManyToManyField(
                blank=True, related_name="views", to="viewer.viewer"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 28, 7, 23, 0, 196179, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
