# Generated by Django 4.2.2 on 2023-06-28 13:24

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0011_alter_news_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                related_name="news_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 28, 13, 24, 11, 793770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
