# Generated by Django 4.2.2 on 2023-07-09 08:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0014_alter_news_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="news_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 9, 8, 25, 43, 750758, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                max_length=250, unique_for_date="publish", verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="news",
            name="viewes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="views", to="viewer.viewer"
            ),
        ),
    ]
